import '../styles/global.css';

export const metadata = {
   title: 'Welcome to client',
   description: 'Generated by create-nx-workspace',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
   <html lang="en">
      <body>{children}</body>
   </html>
);

export default RootLayout;
